<?php
require __DIR__ . '/../../app/bootstrap.php'; require_admin();
[$periodKey,$periodLabel,$start,$end]=allowed_period();$pdo=db();
$query="SELECT p.id,p.name,p.slug,p.price_fcfa,
 COALESCE((SELECT SUM(sm.quantity) FROM stock_movements sm WHERE sm.product_id=p.id),0) stock,
 COALESCE((SELECT SUM(o.quantity) FROM orders o WHERE o.product_id=p.id AND o.status='Livrée' AND DATE(o.created_at) BETWEEN ? AND ?),0) units,
 COALESCE((SELECT SUM(o.quantity*o.unit_price_fcfa) FROM orders o WHERE o.product_id=p.id AND o.status='Livrée' AND DATE(o.created_at) BETWEEN ? AND ?),0) revenue,
 COALESCE((SELECT SUM(COALESCE(sm.purchase_price_fcfa,0)+COALESCE(sm.transit_price_fcfa,0))/NULLIF(SUM(sm.quantity),0) FROM stock_movements sm WHERE sm.product_id=p.id AND sm.movement_type='Réassort'),0) unit_cost,
 COALESCE((SELECT SUM(ac.amount_fcfa) FROM ad_costs ac WHERE ac.product_id=p.id AND ac.start_date <= ? AND ac.end_date >= ?),0) ad_spend
 FROM products p ORDER BY revenue DESC";
$stmt=$pdo->prepare($query);$stmt->execute([$start,$end,$start,$end,$end,$start]);$rows=$stmt->fetchAll();foreach($rows as &$row){$row['gross_margin']=$row['revenue']-($row['units']*$row['unit_cost'])-$row['ad_spend'];$row['cac']=$row['units']>0&&$row['ad_spend']>0?$row['ad_spend']/$row['units']:null;}$sort=(string)($_GET['sort']??'revenue');$allowedSort=['revenue','gross_margin','units','cac'];usort($rows,function($a,$b)use($sort){if($sort==='cac'){return ($a['cac']??INF)<=>($b['cac']??INF);}return $b[$sort]<=>$a[$sort];});$bestRevenue=$rows[0]??null;$bestMargin=$rows;usort($bestMargin,fn($a,$b)=>$b['gross_margin']<=>$a['gross_margin']);$bestMargin=$bestMargin[0]??null;$lowestStock=$rows;usort($lowestStock,fn($a,$b)=>$a['stock']<=>$b['stock']);$lowestStock=$lowestStock[0]??null;
$adminPageTitle='Analyse produits';require APP_ROOT.'/templates/admin-header.php';
?>
<header class="admin-page-head"><div><p class="admin-kicker">Analyse produits</p><h1>Voir ce qui est vraiment rentable.</h1><p>Chiffre d’affaires, marge, publicité et CAC sont calculés sur la période choisie.</p></div><form class="admin-period" method="get"><input type="hidden" name="sort" value="<?= e($sort) ?>"><?php foreach(['today'=>'Aujourd’hui','7'=>'7 jours','14'=>'14 jours','30'=>'30 jours','90'=>'90 jours','month'=>'Ce mois','quarter'=>'Trimestre','year'=>'Cette année'] as $key=>$label): ?><a class="<?= $periodKey===$key?'active':'' ?>" href="?<?= e(http_build_query(['period'=>$key,'sort'=>$sort])) ?>"><?= $label ?></a><?php endforeach; ?><input type="hidden" name="period" value="custom"><span class="custom-period"><input type="date" name="start" value="<?= e($start) ?>"><input type="date" name="end" value="<?= e($end) ?>"><button class="admin-button">Choisir</button></span></form></header>
<section class="metric-grid"><article class="metric"><p>Meilleur CA</p><strong><?= e($bestRevenue['name']??'—') ?></strong><span><?= money((float)($bestRevenue['revenue']??0)) ?></span></article><article class="metric"><p>Meilleure marge</p><strong><?= e($bestMargin['name']??'—') ?></strong><span><?= money((float)($bestMargin['gross_margin']??0)) ?></span></article><article class="metric"><p>À sécuriser</p><strong><?= e($lowestStock['name']??'—') ?></strong><span><?= (int)($lowestStock['stock']??0) ?> unité(s) disponible(s)</span></article><article class="metric"><p>Période active</p><strong><?= e($periodLabel) ?></strong><span><?= e($start) ?> → <?= e($end) ?></span></article></section>
<div class="admin-filter"><span style="align-self:center;font-size:12px;font-weight:700">Classer par :</span><?php foreach(['revenue'=>'Chiffre d’affaires','gross_margin'=>'Marge','units'=>'Ventes','cac'=>'CAC Meta'] as $key=>$label): ?><a class="<?= $sort===$key?'admin-button':'' ?>" style="padding:9px 11px;border:1px solid #d3dfeb;border-radius:5px;font-size:11px" href="?<?= e(http_build_query(['period'=>$periodKey,'start'=>$start,'end'=>$end,'sort'=>$key])) ?>"><?= e($label) ?></a><?php endforeach; ?></div>
<section class="admin-panel"><p class="admin-kicker">Classement détaillé</p><h2>Produits par rentabilité.</h2><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>Produit</th><th>Ventes</th><th>CA</th><th>Coût unitaire</th><th>Ads Meta</th><th>CAC Meta</th><th>Marge après ads</th><th>Stock</th></tr></thead><tbody><?php foreach($rows as $index=>$row): ?><tr><td><strong>0<?= $index+1 ?> · <?= e($row['name']) ?></strong><small><?= e($row['slug']) ?></small></td><td><?= (int)$row['units'] ?> unité(s)</td><td><strong><?= money((float)$row['revenue']) ?></strong></td><td><?= $row['unit_cost']?money((float)$row['unit_cost']):'À renseigner' ?></td><td><?= $row['ad_spend']?money((float)$row['ad_spend']):'À renseigner' ?></td><td><?= $row['cac']!==null?money((float)$row['cac']):($row['units']?'Renseignez les ads':'Aucune vente') ?></td><td><strong><?= money((float)$row['gross_margin']) ?></strong></td><td><span class="status <?= $row['stock']<=6?'':'delivered' ?>"><?= (int)$row['stock'] ?> unité(s)</span></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php require APP_ROOT.'/templates/admin-footer.php'; ?>
