<?php
require __DIR__ . '/../../app/bootstrap.php';
require_admin();
[$periodKey, $periodLabel, $start, $end] = allowed_period();
$pdo = db();
$summary = $pdo->prepare("SELECT COALESCE(SUM(quantity * unit_price_fcfa),0) revenue, COUNT(DISTINCT order_ref) orders, COALESCE(AVG(quantity * unit_price_fcfa),0) average_basket FROM orders WHERE status='Livrée' AND DATE(created_at) BETWEEN ? AND ?");
$summary->execute([$start, $end]); $summary = $summary->fetch();
$margin = $pdo->prepare("SELECT COALESCE(SUM(o.quantity * (o.unit_price_fcfa - COALESCE(costs.unit_cost,0))),0) value FROM orders o LEFT JOIN (SELECT product_id, SUM(COALESCE(purchase_price_fcfa,0)+COALESCE(transit_price_fcfa,0))/NULLIF(SUM(CASE WHEN movement_type='Réassort' THEN quantity ELSE 0 END),0) unit_cost FROM stock_movements WHERE movement_type='Réassort' GROUP BY product_id) costs ON costs.product_id=o.product_id WHERE o.status='Livrée' AND DATE(o.created_at) BETWEEN ? AND ?");
$margin->execute([$start, $end]); $margin = (float) ($margin->fetchColumn() ?: 0);
$channels = $pdo->prepare("SELECT COALESCE(acquisition_channel,'À renseigner') channel, COUNT(DISTINCT order_ref) orders, COALESCE(SUM(quantity*unit_price_fcfa),0) revenue FROM orders WHERE status <> 'À confirmer' AND DATE(created_at) BETWEEN ? AND ? GROUP BY acquisition_channel"); $channels->execute([$start,$end]); $channels=$channels->fetchAll();
$ads = $pdo->prepare("SELECT COALESCE(SUM(amount_fcfa),0) FROM ad_costs WHERE start_date <= ? AND end_date >= ?"); $ads->execute([$end,$start]); $adSpend=(float)$ads->fetchColumn();
$stock = $pdo->query("SELECT p.id,p.name,p.slug,p.price_fcfa,COALESCE(SUM(sm.quantity),0) quantity,COALESCE((SELECT SUM(COALESCE(s2.purchase_price_fcfa,0)+COALESCE(s2.transit_price_fcfa,0))/NULLIF(SUM(s2.quantity),0) FROM stock_movements s2 WHERE s2.product_id=p.id AND s2.movement_type='Réassort'),0) unit_cost FROM products p LEFT JOIN stock_movements sm ON sm.product_id=p.id GROUP BY p.id ORDER BY p.id")->fetchAll();
$low = array_filter($stock, fn($item) => (int)$item['quantity'] <= 6);
$recent = $pdo->query("SELECT id,order_ref,customer_first_name,customer_last_name,product_name,variant,quantity,status,unit_price_fcfa,created_at FROM orders ORDER BY created_at DESC LIMIT 6")->fetchAll();
$query = http_build_query(['period'=>$periodKey,'start'=>$start,'end'=>$end]);
$adminPageTitle='Vue d’ensemble'; require APP_ROOT . '/templates/admin-header.php';
?>
<header class="admin-page-head"><div><p class="admin-kicker">Pilotage commercial</p><h1>Voir ce qui fait avancer la boutique.</h1><p><?= e($periodLabel) ?> · les chiffres se basent sur les commandes livrées.</p></div><form class="admin-period" method="get"><?php foreach(['today'=>'Aujourd’hui','7'=>'7 jours','14'=>'14 jours','30'=>'30 jours','90'=>'90 jours','month'=>'Ce mois','quarter'=>'Trimestre','year'=>'Cette année'] as $key=>$label): ?><a class="<?= $periodKey===$key?'active':'' ?>" href="?period=<?= $key ?>"><?= $label ?></a><?php endforeach; ?><input type="hidden" name="period" value="custom"><span class="custom-period"><input type="date" name="start" value="<?= e($start) ?>"><input type="date" name="end" value="<?= e($end) ?>"><button class="admin-button">Choisir</button></span></form></header>
<section class="metric-grid"><article class="metric"><p>Chiffre d’affaires</p><strong><?= money((float)$summary['revenue']) ?></strong><span><?= (int)$summary['orders'] ?> commandes livrées</span></article><article class="metric"><p>Marge brute estimée</p><strong><?= money($margin) ?></strong><span>Coût unitaire issu des réassorts</span></article><article class="metric"><p>CAC Meta</p><strong><?= $adSpend > 0 && (int)$summary['orders'] > 0 ? money($adSpend / (int)$summary['orders']) : 'À renseigner' ?></strong><span><?= $adSpend > 0 ? money($adSpend).' de publicité' : 'Renseignez les coûts publicitaires' ?></span></article><article class="metric"><p>Panier moyen</p><strong><?= money((float)$summary['average_basket']) ?></strong><span><?= e($periodLabel) ?></span></article></section>
<section class="admin-grid"><article class="admin-panel"><div class="admin-panel__head"><div><p class="admin-kicker">À traiter</p><h2>Commandes récentes</h2></div><a href="<?= e(url('/admin/orders.php')) ?>">Tout voir</a></div><div class="mini-table"><?php foreach($recent as $order): ?><div><span><strong><?= e($order['customer_first_name'].' '.$order['customer_last_name']) ?></strong><small><?= e($order['order_ref']) ?> · <?= e($order['product_name']) ?> · <?= e($order['variant']) ?></small></span><span class="status <?= $order['status']==='Livrée'?'delivered':($order['status']==='En livraison'?'delivery':'') ?>"><?= e($order['status']) ?></span><strong><?= money($order['quantity']*$order['unit_price_fcfa']) ?></strong></div><?php endforeach; ?><?php if(!$recent): ?><div><span>Aucune commande pour le moment.</span></div><?php endif; ?></div></article><article class="admin-panel"><p class="admin-kicker">Acquisition</p><h2>Canaux suivis</h2><div class="channel-list"><?php foreach($channels as $channel): ?><div><strong><?= e($channel['channel']) ?></strong><b><?= money((float)$channel['revenue']) ?></b><span><?= (int)$channel['orders'] ?> commande(s)</span><span><?= $channel['channel']==='Meta' && $adSpend > 0 && $channel['orders'] ? 'CAC '.money($adSpend/(int)$channel['orders']) : ($channel['channel']==='Meta'?'Coûts Meta à renseigner':'Sans dépense attribuée') ?></span></div><?php endforeach; ?><?php if(!$channels): ?><p>Aucun canal renseigné sur cette période.</p><?php endif; ?></div></article></section>
<?php if($low): ?><section class="admin-panel low-stock" style="margin-top:14px"><p class="admin-kicker">Stock à surveiller</p><h2><?= count($low) ?> modèle(s) atteignent le seuil de 6 unités.</h2><p><?php foreach($low as $item): ?><strong><?= e($item['name']) ?></strong> : <?= (int)$item['quantity'] ?> unité(s) · <?php endforeach; ?></p><a class="admin-button" href="<?= e(url('/admin/stock.php')) ?>">Mettre le stock à jour</a></section><?php endif; ?>
<?php require APP_ROOT . '/templates/admin-footer.php'; ?>
